/* confdefs.h */
#define PACKAGE_NAME "pluto"
#define PACKAGE_TARNAME "pluto"
#define PACKAGE_VERSION "0.12.0"
#define PACKAGE_STRING "pluto 0.12.0"
#define PACKAGE_BUGREPORT "udayb@iisc.ac.in"
#define PACKAGE_URL ""
#define PACKAGE "pluto"
#define VERSION "0.12.0"
#define HAVE_CXX11 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_MATH_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDIO_H 1
#define HAVE_ASSERT_H 1
#define HAVE_STRING_H 1
#define HAVE_DECL_MP_GET_MEMORY_FUNCTIONS 1
